### ISSUE TITLE
Update the colors

### ISSUE THREAD

**Issue by darckyn** [TerryMooreII/materialize-social#1]
Hi, how are you?

I'm using your tool and I'm really enjoying it, but I think you need an update on the colors used in social networking.

Like the Instagram that had a color change in its logo.

In instagram I changed the color to that indicated in this site: [Social Colors](https://www.materialui.co/socialcolors)

Could you please update the colors of social networks?

Thank you very much.

**Comment by TerryMooreII** [comment]
I changed the instragram color but I used the first color from this site 
https://brandcolors.net/

**Comment by darckyn** [comment]
Thanks
