### ISSUE TITLE
Update to angular 4

### ISSUE THREAD

**Issue by lgLindstrom** [TerryMooreII/materialize-social#4]
Hi

I've developing a angular4/material application. When installing I get this message.

> npm WARN deprecated angular2@2.0.0-beta.21: This version of Angular has been deprecated. Use @angular/core instead.
npm WARN angular2@2.0.0-beta.21 requires a peer of es6-shim@^0.35.0 but none was installed.

Would it be possible for you to update to latest and greatest versions ?

**Comment by TerryMooreII** [comment]
Materialize-social isnt dependant on angular. Please check your other dependencies.  https://github.com/TerryMooreII/materialize-social/blob/master/package.json
